build.gradle.kts
src/main/kotlin/uw/cse403/floorit/FloorItApplication.kt
src/test/kotlin/uw/cse403/floorit/FloorItApplicationTests.kt
src/test/kotlin/uw/cse403/floorit/TestFloorItApplication.kt
src/test/kotlin/uw/cse403/floorit/TestcontainersConfiguration.kt

Fixing gradle build
None
Renamed filename to match class name

(refactoring): Fixing gradle build and tests

---

Weekly-Reports/weekly_template.md
weekly-reports/Floorit1.28.2025.md

MY WEEKLY REPORT
[INSERT HERE]
None
Assigned tickets and UI designs
[INSERT HERE]

(WR): Andrew's weekly report Jan 21 - Jan 28

---

weekly-reports/Floorit1.28.2025.md

Example: I am adding the mapping of images to their associated words with comprehensive tests
Update weekly report.
Example: I decided to add two DTO classes to needed to encapsulate the data to
store the mapping of images to their associated words. I have tested blah blah blah
N/A
N/A

weekly report

---

weekly-reports/Floorit1.28.2025.md

Added individual contributions to weekly report.
[n/a]
[n/a]
[n/a]

Completed individual contributions to weekly report

---

BJJ
weekly-reports/Floorit1.28.2025.md

I added my progress for this week!

Added my project progression

---

weekly-reports/Floorit2.4.2025.md

I think it should be working now hopefully

Added weekly report for week 2

---

weekly-reports/Floorit1.28.25.md

Added Weekly Update
No Ticket, but weekly update
Was missing my weekly update
Now has my weekly update
No need for testing

weekly update

---

README.md

Small typo to set up repo for future users
None, but we want to allow anyone to clone our REPO
git clone command is invalid
Fixed git command to clone
Too lazy to try to clone it.

(files): Read Me Git Clone is WRONG!

---

weekly-reports/Floorit2.4.2025.md

Added section under weekly report for week of Feb. 5th + meeting agenda
[n/a]
[n/a]
[n/a] (no change)
[n/a]

Added weekly report + meeting agenda

---

frontend/public/category_data/lol_champion_titles.json

Fixing JSON file
Administering a new fix
Failing Lint
Passing lint
[INSERT HERE]

(fix): Fixing Linter Issues

---

weekly-reports/Floorit2.11.2025.md

(WP): February 12th Weekly Report

---

weekly-reports/Floorit-2.19.2025.md

Weekly Report for 2/12/2025
N/A
N/A
N/A
N/A

Weeky Report 2.19

---

README.md

An improved version of your README with the required user and developer documentation integrated.
https://courses.cs.washington.edu/courses/cse403/25wi/project/06_beta_plusplus.html
Vague readme
Detailed readme
[INSERT HERE]

(Documentation): Main Readme Updated

---

backend/Makefile
backend/README.md

Updated instructions to run the backend application. We still need documentation for developers as to how to add a category.
None
Documentations not comprehensive for window users
Added additional information for windows
None

(Documentation): Backend Readme updated

---

frontend/src/utils/shuffler.test.ts

Added Shuffler Test
None
No shuffler test currently
Shuffler tests are added
CI tools

(test): Shuffler Test

---

frontend/package-lock.json
frontend/package.json
frontend/src/screens/Game/components/Player/Timer/Timer.test.tsx
frontend/src/setupTests.ts
frontend/tsconfig.app.json
frontend/vite.config.ts

Added Timer Tests with needed dependencies to test tsx components
None
There were no timer tests
there are new Timer tests
inactive timer, timer started, timer not in game, timer timeout, timer reset

(tests): Timer Tests

---

frontend/src/screens/Game/components/Player/Player.test.tsx
frontend/src/screens/Game/components/Player/Player.tsx

Added Player tests
None
There were no player tests
There are player tests now
Tested winner, player's active, player inactive, player's time run out

(test) Added Player Tests

---

frontend/src/screens/Game/components/Display/GameDisplay/TriviaQuestion.test.tsx
frontend/src/screens/Game/components/Display/GamePreview/GamePreview.test.tsx

Added Question and GamePreview component tests
None
No current tests
New tests for these child components
Tests that the components renders and utilizes memo correctly

(test): Display Props Test

---

frontend/src/contexts/AppContext.tsx
frontend/src/screens/Game/GameScreen.test.tsx
frontend/src/screens/Game/components/Display/Display.test.tsx

Created integration tests for Game screen
None
No integration test
Created tests for game screen
Utilized mocked child components to simulate a true runthrough of the game screen application

(test): GameScreen Integration Test

---

frontend/package-lock.json
frontend/package.json
frontend/src/screens/Game/GameScreen.test.tsx
frontend/src/screens/Game/GameScreen.tsx
frontend/src/screens/Game/components/WinningModal/WinningModal.style.ts
frontend/src/screens/Game/components/WinningModal/WinningModal.test.tsx
frontend/src/screens/Game/components/WinningModal/WinningModal.tsx

Added a satisfying win screen
[ticket-13](https://github.com/apnguyen1/floor-it/issues/13)
There was no real winning screen before
There is now a winning screen with confetti

(QOL): Added Winning Modal

---

README.md

The title
[INSERT HERE]
[INSERT HERE]
[INSERT HERE]

(release): Beta++ Release

---

frontend/src/components/Settings/SettingModal.style.ts
frontend/src/components/Settings/SettingModal.tsx
frontend/src/contexts/AppContext.tsx
frontend/src/screens/Avatars/AvatarScreen.tsx
frontend/src/screens/Game/GameScreen.style.ts
frontend/src/screens/Game/GameScreen.test.tsx
frontend/src/screens/Game/GameScreen.tsx
frontend/src/screens/Game/components/Player/Player.test.tsx
frontend/src/screens/Game/components/Player/Player.tsx
frontend/src/screens/Game/components/Player/Timer/Timer.style.tsx
frontend/src/screens/Game/components/Player/Timer/Timer.test.tsx
frontend/src/screens/Game/components/Player/Timer/Timer.tsx
frontend/src/screens/Game/components/WinningModal/WinningModal.test.tsx
frontend/src/types/global.type.ts

Added the option for users to change their timers in increments of 5
[ticket-114](https://github.com/apnguyen1/floor-it/issues/114)
Hardcoded start time of 30 seconds
Users are able to choose a initial timer for themselves

(component): Added Custom Timers

---

weekly-reports/FloorIt-2.25.2025.md

[INSERT HERE]
[INSERT HERE]
[INSERT HERE]
[INSERT HERE]

(wp): Feb 25 Weekly Report

---

backend/src/scripts/lol_champions.py
backend/src/scripts/numbers.py
frontend/public/category_data/lol_champion_titles.json

[INSERT HERE]
[INSERT HERE]
[INSERT HERE]
[INSERT HERE]

(styling): fixed styling

---

frontend/src/screens/Categories/CategoriesScreen.style.ts
frontend/src/screens/Categories/CategoriesScreen.tsx
frontend/src/screens/Categories/components/CategoriesGrid/CategoriesGrid.style.ts
frontend/src/screens/Categories/components/CategoriesGrid/CategoriesGrid.tsx
frontend/src/screens/Categories/components/SearchBar/SearchBar.style.ts
frontend/src/screens/Categories/components/SearchBar/SearchBar.tsx
frontend/src/screens/Categories/components/SelectionBar/SelectionBar.style.ts
frontend/src/screens/Categories/components/SelectionBar/SelectionBar.tsx

Modularised files under Categories view.
[ticket-119](https://github.com/apnguyen1/floor-it/issues/119)
Everything aggregated into a few large files
Cleaner setup following formatting for Games view
No tests added.

Modularised files under Categories view

---

README.md
frontend/README.md

Addressing the issue of undisclosed browser support and compatibility 
[ticket-162)(https://github.com/apnguyen1/floor-it/issues/162)
Non-existent disclosure of supported browsers
Added both to developer and user docs
[INSERT HERE]

(Documentation): Browser unsupported documentation

---

frontend/src/components/Settings/SettingModal.tsx
frontend/src/contexts/AppContext.tsx
frontend/src/screens/Game/GameScreen.tsx
frontend/src/screens/Game/components/Display/Display.style.ts
frontend/src/screens/Game/components/Display/Display.test.tsx
frontend/src/screens/Game/components/Display/Display.tsx
frontend/src/screens/Game/components/WinningModal/WinningModal.test.tsx

Added initial user text input. List of oversight(s):
- skip functionality should be changed (i.e. should not be pressing space to skip anymore; find an alternative)
- skip text prompt should be changed to match the above and remove mentions of mic access
[ticket-173](https://github.com/apnguyen1/floor-it/issues/173)
Users cannot use text input to play game.
Users can use text input to play game.
No tests added yet in Display.test.tsx (minor changes made to allow previous tests to work)

Added initial user text input

---

.pre-commit-config.yaml
backend/src/scripts/text_categories.py
backend/src/utils/text_category.py
frontend/public/category_data/antonyms.json
frontend/public/category_data/brazilian_jiu-jitsu.json
frontend/public/category_preview_list.json

Alongside with new category, added CI for automating running backend main method with every new backend change.
None
No antonym category
new antonym category
Fixing this bug

(category): Added Antonyms

---

backend/src/resources/static/pokemon_kanto.json
backend/src/scripts/pokemon_kanto.py
frontend/public/category_data/original_151_pokémon.json
frontend/public/category_preview_list.json
package-lock.json

Added .json file and scripts for new Pokémon category.
[ticket-198](https://github.com/apnguyen1/floor-it/issues/198)

Added new category for gameplay: Pokémon

---

backend/src/resources/static/cse403_finals.txt
backend/src/scripts/text_categories.py
frontend/public/category_data/cse_403_2025_finals.json
frontend/public/category_preview_list.json

[INSERT HERE]
[INSERT HERE]
[INSERT HERE]
[INSERT HERE]

(category): CSE 403 final

---

backend/src/scripts/text_categories.py
frontend/public/category_data/brazilian_jiu-jitsu.json
frontend/public/category_data/food_and_drinks.json
frontend/public/category_preview_list.json

Fixed fuzzy matching for food and drink

Fixed fuzzy

---

backend/src/scripts/taylor_swift.py
backend/src/utils/download_kaggle_dataset.py
frontend/public/category_data/taylor_swift_songs.json
frontend/public/category_preview_list.json

[INSERT HERE]
[INSERT HERE]
[INSERT HERE]
[INSERT HERE]

(category): Taylor Swift Songs
